# Generated by Django 4.1.7 on 2023-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0002_task_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
