# Generated by Django 4.1.7 on 2023-03-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0003_task_planned_end_task_planned_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_end',
            field=models.DateTimeField(blank=True, default='2021-08-02 00:00', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_start',
            field=models.DateTimeField(blank=True, default='2021-04-02 00:00', null=True),
        ),
    ]
