# Generated by Django 4.1.7 on 2023-03-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0004_alter_task_planned_end_alter_task_planned_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_end',
            field=models.DateTimeField(default='2021-08-02 00:00'),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_start',
            field=models.DateTimeField(default='2021-04-02 00:00'),
        ),
    ]
