# Generated by Django 4.1.7 on 2023-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0006_alter_task_planned_end_alter_task_planned_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
