# Generated by Django 4.1.7 on 2023-03-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0007_alter_task_planned_end_alter_task_planned_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
