# Generated by Django 4.1.7 on 2023-03-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0008_task_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
