# Generated by Django 4.1.7 on 2023-03-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0009_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('lag', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
