# Generated by Django 4.1.7 on 2023-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0010_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='capacity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
