# Generated by Django 4.1.7 on 2023-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0013_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ob_fact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ob_plan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
