# Generated by Django 4.1.7 on 2023-03-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0014_task_ob_fact_task_ob_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='render',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
