# Generated by Django 4.1.7 on 2023-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0015_task_render'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='capacity',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
