# Generated by Django 4.1.7 on 2023-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0016_alter_task_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='open',
            field=models.BooleanField(default=1),
        ),
    ]
