# Generated by Django 4.1.7 on 2023-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0017_task_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_start',
            field=models.DateTimeField(),
        ),
    ]
