# Generated by Django 4.1.7 on 2023-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0018_alter_task_planned_end_alter_task_planned_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resourceOn',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
