# Generated by Django 4.1.7 on 2023-03-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0021_alter_task_planned_end_alter_task_planned_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
