# Generated by Django 4.1.7 on 2023-03-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0022_alter_task_duration_alter_task_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='open',
        ),
    ]
