# Generated by Django 4.1.7 on 2023-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0023_remove_task_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='open',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
