# Generated by Django 4.1.7 on 2023-03-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0024_task_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, default='project', max_length=20, null=True),
        ),
    ]
