# Generated by Django 4.1.7 on 2023-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0025_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resourceOn',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
