# Generated by Django 4.1.7 on 2023-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0029_rename_resource_task_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hide_bar',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
