# Generated by Django 4.1.7 on 2023-04-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0030_task_hide_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hide_bar',
        ),
    ]
